### ISSUE TITLE
info required for storage provisor

### ISSUE THREAD

**Issue by vikasgubbi** [hoeghh/kubernetes_the_easy_way#42]
Hi,

currently which storage provisor is being used for the setup.

Regards,Vikas

**Comment by hoeghh** [comment]
I install nfs on each client, so nfs can be used.

Example : 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-postgres-pv
  labels:
    volume-type: jira-postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-server.example.com
    path: /home/nfsshare/jira-postgres
```

Then in the config file, add the ip and dns for the nfs, so that each node can resolve them.
```
export EXTRA_HOSTS="\n
# Add extra hosts entries to each node in the format of \n 
192.168.1.148 nfs-server.example.com                       "
```
